version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: clipforge-postgres
    environment:
      POSTGRES_DB: clipforge_ai
      POSTGRES_USER: clipforge
      POSTGRES_PASSWORD: clipforge_dev_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clipforge -d clipforge_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for BullMQ job queues
  redis:
    image: redis:7-alpine
    container_name: clipforge-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass clipforge_redis_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Redis Insight for monitoring (optional)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: clipforge-redis-insight
    ports:
      - '8001:8001'
    depends_on:
      - redis
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: clipforge-network
    driver: bridge